import os
import subprocess

def convert_midi_to_wav(midi_file, output_folder):
    wav_file = os.path.join(output_folder, os.path.splitext(os.path.basename(midi_file))[0] + ".wav")
    # Use ffmpeg to convert MIDI to WAV
    print('ffmpeg', '-i', midi_file, wav_file)

    return wav_file

def batch_convert_midi_to_wav(input_folder, output_folder):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    for file_name in os.listdir(input_folder):
        #print(file_name)
        if file_name.endswith(".mid") or file_name.endswith(".midi"):
            midi_file = input_folder + file_name
            #print(midi_file)
            convert_midi_to_wav(midi_file, output_folder)
            #print(f"Converted: {midi_file}")

if __name__ == "__main__":
    input_folder = r"C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\"
    output_folder = r"C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\"

    batch_convert_midi_to_wav(input_folder, output_folder)
    
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_1.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_1.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_10.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_10.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_100.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_100.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_101.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_101.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_102.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_102.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_103.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_103.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_104.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_104.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_105.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_105.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_106.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_106.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_107.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_107.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_108.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_108.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_109.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_109.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_11.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_11.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_110.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_110.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_111.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_111.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_112.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_112.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_113.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_113.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_114.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_114.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_115.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_115.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_116.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_116.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_117.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_117.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_118.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_118.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_119.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_119.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_12.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_12.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_120.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_120.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_121.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_121.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_122.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_122.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_123.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_123.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_124.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_124.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_125.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_125.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_126.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_126.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_127.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_127.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_128.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_128.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_129.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_129.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_13.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_13.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_130.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_130.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_131.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_131.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_132.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_132.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_133.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_133.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_134.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_134.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_135.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_135.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_136.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_136.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_137.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_137.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_138.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_138.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_139.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_139.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_14.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_14.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_140.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_140.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_141.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_141.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_142.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_142.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_143.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_143.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_144.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_144.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_145.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_145.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_146.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_146.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_147.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_147.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_148.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_148.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_149.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_149.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_15.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_15.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_150.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_150.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_151.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_151.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_152.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_152.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_153.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_153.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_154.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_154.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_155.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_155.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_156.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_156.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_157.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_157.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_158.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_158.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_159.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_159.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_16.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_16.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_160.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_160.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_161.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_161.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_162.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_162.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_163.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_163.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_164.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_164.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_165.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_165.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_166.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_166.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_167.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_167.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_168.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_168.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_169.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_169.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_17.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_17.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_170.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_170.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_171.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_171.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_172.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_172.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_173.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_173.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_174.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_174.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_175.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_175.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_176.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_176.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_177.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_177.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_178.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_178.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_179.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_179.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_18.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_18.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_180.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_180.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_181.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_181.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_182.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_182.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_183.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_183.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_184.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_184.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_185.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_185.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_186.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_186.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_187.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_187.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_188.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_188.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_189.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_189.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_19.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_19.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_190.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_190.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_191.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_191.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_192.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_192.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_193.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_193.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_194.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_194.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_195.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_195.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_196.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_196.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_197.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_197.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_198.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_198.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_199.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_199.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_2.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_2.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_20.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_20.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_200.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_200.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_201.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_201.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_202.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_202.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_203.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_203.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_204.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_204.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_205.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_205.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_206.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_206.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_207.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_207.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_208.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_208.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_209.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_209.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_21.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_21.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_210.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_210.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_211.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_211.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_212.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_212.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_213.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_213.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_214.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_214.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_215.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_215.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_216.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_216.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_217.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_217.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_218.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_218.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_219.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_219.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_22.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_22.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_220.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_220.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_221.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_221.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_222.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_222.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_223.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_223.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_224.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_224.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_225.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_225.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_226.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_226.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_227.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_227.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_228.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_228.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_229.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_229.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_23.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_23.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_230.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_230.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_231.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_231.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_232.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_232.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_233.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_233.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_234.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_234.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_235.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_235.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_236.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_236.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_237.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_237.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_238.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_238.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_239.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_239.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_24.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_24.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_240.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_240.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_241.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_241.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_242.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_242.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_243.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_243.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_244.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_244.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_245.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_245.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_246.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_246.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_247.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_247.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_248.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_248.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_249.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_249.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_25.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_25.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_250.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_250.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_251.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_251.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_252.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_252.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_253.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_253.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_254.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_254.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_255.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_255.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_256.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_256.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_257.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_257.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_258.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_258.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_259.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_259.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_26.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_26.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_260.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_260.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_261.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_261.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_262.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_262.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_263.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_263.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_264.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_264.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_265.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_265.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_266.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_266.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_267.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_267.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_268.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_268.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_269.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_269.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_27.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_27.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_270.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_270.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_271.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_271.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_272.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_272.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_273.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_273.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_274.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_274.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_275.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_275.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_276.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_276.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_277.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_277.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_278.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_278.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_279.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_279.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_28.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_28.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_280.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_280.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_281.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_281.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_282.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_282.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_283.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_283.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_284.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_284.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_285.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_285.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_286.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_286.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_287.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_287.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_288.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_288.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_289.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_289.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_29.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_29.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_290.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_290.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_291.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_291.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_292.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_292.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_293.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_293.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_294.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_294.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_295.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_295.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_296.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_296.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_297.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_297.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_298.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_298.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_299.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_299.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_3.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_3.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_30.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_30.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_300.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_300.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_301.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_301.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_302.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_302.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_303.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_303.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_304.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_304.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_305.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_305.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_306.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_306.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_307.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_307.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_308.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_308.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_309.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_309.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_31.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_31.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_32.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_32.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_33.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_33.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_34.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_34.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_35.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_35.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_36.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_36.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_37.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_37.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_38.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_38.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_39.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_39.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_4.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_4.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_40.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_40.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_41.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_41.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_42.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_42.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_43.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_43.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_44.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_44.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_45.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_45.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_46.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_46.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_47.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_47.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_48.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_48.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_49.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_49.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_5.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_5.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_50.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_50.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_51.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_51.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_52.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_52.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_53.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_53.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_54.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_54.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_55.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_55.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_56.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_56.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_57.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_57.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_58.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_58.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_59.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_59.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_6.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_6.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_60.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_60.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_61.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_61.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_62.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_62.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_63.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_63.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_64.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_64.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_65.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_65.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_66.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_66.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_67.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_67.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_68.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_68.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_69.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_69.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_7.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_7.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_70.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_70.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_71.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_71.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_72.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_72.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_73.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_73.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_74.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_74.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_75.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_75.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_76.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_76.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_77.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_77.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_78.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_78.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_79.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_79.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_8.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_8.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_80.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_80.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_81.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_81.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_82.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_82.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_83.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_83.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_84.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_84.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_85.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_85.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_86.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_86.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_87.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_87.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_88.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_88.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_89.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_89.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_9.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_9.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_90.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_90.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_91.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_91.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_92.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_92.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_93.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_93.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_94.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_94.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_95.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_95.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_96.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_96.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_97.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_97.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_98.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_98.wav
ffmpeg -i C:\Users\Gus\Documents\GitHub\Music-AI-Gen\data\\music_99.mid C:\Users\Gus\Documents\GitHub\Music-AI-Gen\wav\\music_99.wav